# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_class', models.IntegerField(default=0)),
                ('image_class_desc', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_location', models.CharField(max_length=500)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image_class_0', models.IntegerField(default=0)),
                ('image_class_1', models.IntegerField(default=0)),
                ('image_class_2', models.IntegerField(default=0)),
                ('image_class_3', models.IntegerField(default=0)),
                ('image_class_4', models.IntegerField(default=0)),
                ('image_class_5', models.IntegerField(default=0)),
                ('image_class_6', models.IntegerField(default=0)),
                ('image_class_7', models.IntegerField(default=0)),
            ],
        ),
    ]
