# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160705_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='image_vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
