# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_classes_image_vote_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_class',
            new_name='image_class_0',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='image_vote_count',
        ),
        migrations.AddField(
            model_name='image',
            name='image_class_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='image_class_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='image_class_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='image_class_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='image_class_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='image_class_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='image_class_7',
            field=models.IntegerField(default=0),
        ),
    ]
